global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeapi'
    static_configs:
      - targets: ['nodeapi:3000']

  - job_name: 'mongo-prom-exporter'
    static_configs:
      - targets: ['mongo-prom-exporter:9216']
    
  - job_name: 'nginx-prometheus-exporter'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'prometheus-node-exporter'
    static_configs:
      - targets: ['prometheus-node-exporter:9100']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3001']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']