server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      refresh_interval: 5s
  relabel_configs:
    # Extract the container name (strip the leading slash)
    - source_labels: [__meta_docker_container_name]
      regex: "/(.*)"
      target_label: container_name
    # Optionally capture the container ID
    - source_labels: [__meta_docker_container_id]
      target_label: container_id

- job_name: system_logs
  static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
        __label__: varlogs