apiVersion: 1
policies:
  - orgId: 1
    receiver: "Vikash"
    group_by:
      - 'alertname'
    matchers:
      # - alertname =~ ".*"
      - alertname="InstanceDown"
      - severity="critical"
    continue: false
    mute_timings: []
    routes: []